import { Injectable } from '@angular/core';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

@Injectable({
  providedIn: 'root'
})
export class ExportService {

  constructor() { }

  /**
   * Export JSON data to Excel file
   * @param data Array of objects to export
   * @param fileName Name of the file (without extension)
   * @param sheetName Name of the worksheet
   */
  exportToExcel(data: any[], fileName: string, sheetName: string = 'Data'): void {
    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
    
    // Auto-size columns
    const max_width = data.reduce((w, r) => Math.max(w, Object.keys(r).length), 10);
    worksheet['!cols'] = Array(max_width).fill({ wch: 15 });

    XLSX.writeFile(workbook, `${fileName}_${new Date().getTime()}.xlsx`);
  }

  /**
   * Export table data to PDF
   * @param headers Array of column headers
   * @param data Array of arrays representing rows
   * @param fileName Name of the file (without extension)
   * @param title Optional title to display at the top
   */
  exportToPdf(headers: string[], data: any[][], fileName: string, title?: string): void {
    const doc = new jsPDF();
    
    // Add enterprise header styling
    if (title) {
      doc.setFontSize(18);
      doc.setTextColor(40);
      doc.text(title, 14, 22);
      
      doc.setFontSize(10);
      doc.setTextColor(100);
      const today = new Date().toLocaleString();
      doc.text(`Generated by Inventory Management System | ${today}`, 14, 30);
      
      // Draw a line
      doc.setDrawColor(200, 200, 200);
      doc.line(14, 33, 196, 33);
    }

    autoTable(doc, {
      head: [headers],
      body: data,
      startY: title ? 38 : 10,
      theme: 'grid',
      styles: { 
        fontSize: 8, 
        cellPadding: 3,
        overflow: 'linebreak',
        font: 'helvetica'
      },
      headStyles: { 
        fillColor: [79, 70, 229], // Brand primary
        textColor: 255,
        fontStyle: 'bold',
        halign: 'center'
      },
      alternateRowStyles: {
        fillColor: [245, 247, 250]
      },
      margin: { top: 38 },
      didDrawPage: (dataArg) => {
        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
          `Page ${dataArg.pageNumber}`,
          dataArg.settings.margin.left,
          doc.internal.pageSize.height - 10
        );
      }
    });

    doc.save(`${fileName}_${new Date().getTime()}.pdf`);
  }
}
